openapi: 3.0.3
info:
  title: Tutoria API
  version: 1.0.0
  description: API documentation for Tutoria project
paths:
  /:
    get:
      operationId: root_retrieve
      description: Home view that returns a simple welcome message.
      security:
      - {}
      responses:
        '200':
          description: No response body
  /academic-profile/create/:
    post:
      operationId: academic_profile_create_create
      tags:
      - academic-profile
      responses:
        '200':
          description: No response body
  /academic-profile/edit/:
    put:
      operationId: academic_profile_edit_update
      tags:
      - academic-profile
      responses:
        '200':
          description: No response body
    patch:
      operationId: academic_profile_edit_partial_update
      tags:
      - academic-profile
      responses:
        '200':
          description: No response body
  /api/token/:
    post:
      operationId: api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /availability/create/:
    post:
      operationId: availability_create_create
      description: |-
        Create multiple availability slots for the authenticated teacher.
        Expects a list of availability slot data in the request body.
      tags:
      - availability
      responses:
        '200':
          description: No response body
  /availability/edit/:
    put:
      operationId: availability_edit_update
      description: |-
        Edit multiple availability slots for the authenticated teacher.
        Expects a list of slot updates, each with an 'id' field.
      tags:
      - availability
      responses:
        '200':
          description: No response body
    patch:
      operationId: availability_edit_partial_update
      description: |-
        Edit multiple availability slots for the authenticated teacher.
        Expects a list of slot updates, each with an 'id' field.
      tags:
      - availability
      responses:
        '200':
          description: No response body
  /filter-teachers/:
    get:
      operationId: filter_teachers_retrieve
      description: |-
        Retrieve a filtered list of TeacherProfile overviews.
        Filters: min_salary, max_salary, gender, grade, distance (optional).
      tags:
      - filter-teachers
      responses:
        '200':
          description: No response body
  /grade-by-medium/:
    get:
      operationId: grade_by_medium_retrieve
      description: |-
        Retrieve a list of subjects filtered by the given medium ID.
        Expects 'medium_id' as a GET parameter.
      tags:
      - grade-by-medium
      security:
      - {}
      responses:
        '200':
          description: No response body
  /mediums/:
    get:
      operationId: mediums_retrieve
      description: Retrieve a list of all available mediums.
      tags:
      - mediums
      security:
      - {}
      responses:
        '200':
          description: No response body
  /protected/:
    get:
      operationId: protected_retrieve
      description: A protected view that requires authentication.
      tags:
      - protected
      responses:
        '200':
          description: No response body
  /qualification/create/:
    post:
      operationId: qualification_create_create
      tags:
      - qualification
      responses:
        '200':
          description: No response body
  /qualification/edit/:
    put:
      operationId: qualification_edit_update
      tags:
      - qualification
      responses:
        '200':
          description: No response body
    patch:
      operationId: qualification_edit_partial_update
      tags:
      - qualification
      responses:
        '200':
          description: No response body
  /set-location/:
    post:
      operationId: set_location_create
      description: |-
        A protected view to set the user's location.
        Expects a JSON body with a 'location' field.
      tags:
      - set-location
      responses:
        '200':
          description: No response body
  /subject-by-grade/:
    get:
      operationId: subject_by_grade_retrieve
      description: |-
        Retrieve a list of subjects filtered by the given medium ID.
        Expects 'medium_id' as a GET parameter.
      tags:
      - subject-by-grade
      security:
      - {}
      responses:
        '200':
          description: No response body
  /teacher/create/:
    post:
      operationId: teacher_create_create
      tags:
      - teacher
      responses:
        '200':
          description: No response body
  /teacher/edit/:
    put:
      operationId: teacher_edit_update
      tags:
      - teacher
      responses:
        '200':
          description: No response body
    patch:
      operationId: teacher_edit_partial_update
      tags:
      - teacher
      responses:
        '200':
          description: No response body
  /teacher/full-profile/:
    get:
      operationId: teacher_full_profile_retrieve
      description: Retrieve the TeacherProfile, AcademicProfiles, and Qualifications
        for the authenticated user.
      tags:
      - teacher
      responses:
        '200':
          description: No response body
components:
  schemas:
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
