# Generated by Django 5.2.1 on 2025-06-16 03:56

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_teacherprofile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprofile',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates if the academic profile has been validated by an admin.'),
        ),
        migrations.AlterField(
            model_name='academicprofile',
            name='certificates',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=base.models.certificate_upload_to),
        ),
        migrations.AlterField(
            model_name='academicprofile',
            name='degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='academicprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicprofile',
            name='institution',
            field=models.CharField(max_length=25),
        ),
    ]
