# Generated by Django 5.2.1 on 2025-06-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_academicprofile_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='skill',
            field=models.CharField(max_length=100),
        ),
    ]
