# Generated by Django 5.2.1 on 2025-06-16 04:14

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_qualification_validated_alter_qualification_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprofile',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to=base.models.certificate_upload_to),
        ),
    ]
